services:
  transaction_db:
    image: postgres
    env_file:
      - .postgres.env
    ports:
      - "5434:5432"
    volumes:
      - postgres_transactions:/var/lib/postgresql/data

  transaction_service:
    build:
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    env_file:
      - .env
    depends_on:
      - transaction_db
volumes:
  postgres_transactions:
